### ISSUE TITLE
Helm3 error 

### ISSUE THREAD

**Issue by Dgadavin** [awslabs/k8s-cloudwatch-adapter#15]
Hello.

I'm trying to use helm3 and cloudwatch-adapter and faced this an issue. When I install adapter helm stop working with such message:
```
Error: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server could not find the requested resource
```
On helm2 everything is OK.
Thanks for helping

**Comment by Bukashk0zzz** [comment]
Have same issue with Helm 3

**Comment by chankh** [comment]
which version of the adapter are you using? the call to register with custom.metrics.k8s.io should have been removed in v0.7.0

**Comment by Bukashk0zzz** [comment]
chankh/k8s-cloudwatch-adapter:v0.7.0

**Comment by Bukashk0zzz** [comment]
Looks like a problem is with Helm https://github.com/helm/helm/issues/6361

**Comment by Bukashk0zzz** [comment]
As API point custom.metrics not used. You can delete it and helm starts working after that.

```
kubectl delete apiservice v1beta1.custom.metrics.k8s.io
```
