### ISSUE TITLE
Add labels to the metric

### ISSUE THREAD

**Issue by costimuraru** [awslabs/k8s-cloudwatch-adapter#22]
Is there any way to supply a label to the external metric?
We'd like to create a few metrics and then aggregate them when setting a HorizontalPodAutoscaling, as described here: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-more-specific-metrics 

```
    name: `http_requests`
    selector: `verb=GET`
```

> This selector uses the same syntax as the full Kubernetes label selectors. The monitoring pipeline determines how to collapse multiple series into a single value, if the name and selector match multiple series. The selector is additive,

Right now the metricsLabels returned is `null`: 

`kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/myapp-perf-kond/myapp-elb-5xx-requests"  | jq`

`"metricLabels": null`

```json
{
  "kind": "ExternalMetricValueList",
  "apiVersion": "external.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/external.metrics.k8s.io/v1beta1/namespaces/myapp-perf-kond/myapp-elb-5xx-requests"
  },
  "items": [
    {
      "metricName": "myapp-elb-5xx-requests",
      "metricLabels": null,
      "timestamp": "2020-01-29T18:51:25Z",
      "value": "0"
    }
  ]
}
```

**Comment by chankh** [comment]
@costimuraru you can label them as usual, I've just tested with my own setup

```
$ kubectl label externalmetric hello-queue-length env=demo
externalmetric.metrics.aws/hello-queue-length labeled
$ kubectl describe externalmetric hello-queue-length
Name:         hello-queue-length
Namespace:    default
Labels:       env=demo
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"metrics.aws/v1alpha1","kind":"ExternalMetric","metadata":{"annotations":{},"name":"hello-queue-length","namespace":"default...
API Version:  metrics.aws/v1alpha1
Kind:         ExternalMetric
```

**Comment by chankh** [comment]
Closing this since there is no update.
