### ISSUE TITLE
Export metrics to Prometheus

### ISSUE THREAD

**Issue by caiohasouza** [awslabs/k8s-cloudwatch-adapter#24]
Hello!

It's possible export metrics do Prometheus? Just to monitoring?

Regards

**Comment by chankh** [comment]
I think you are looking for this https://github.com/prometheus/cloudwatch_exporter

**Comment by caiohasouza** [comment]
Right, i thought that would be possible export metrics direcly to Prometheus, but Ok. 

Thank you!
