### ISSUE TITLE
k8s-cloudwatch adapter no longer an implementor of custom.metrics API?

### ISSUE THREAD

**Issue by ghostsquad** [awslabs/k8s-cloudwatch-adapter#26]
I noticed that in the readme, it shows some output from a deployment:

```
apiservice.apiregistration.k8s.io/v1beta1.custom.metrics.k8s.io created
apiservice.apiregistration.k8s.io/v1beta1.external.metrics.k8s.io created
clusterrole.rbac.authorization.k8s.io/k8s-cloudwatch-adapter:custom-metrics-reader created
clusterrole.rbac.authorization.k8s.io/k8s-cloudwatch-adapter:external-metrics-reader created
clusterrole.rbac.authorization.k8s.io/k8s-cloudwatch-adapter-resource-reader created
clusterrolebinding.rbac.authorization.k8s.io/k8s-cloudwatch-adapter:custom-metrics-reader created
clusterrolebinding.rbac.authorization.k8s.io/k8s-cloudwatch-adapter:external-metrics-reader created
```

but the manifests here no longer deploy the `APIService` for custom.metrics:

https://github.com/awslabs/k8s-cloudwatch-adapter/blob/master/deploy/adapter.yaml

At one point in the past, maybe it did. Is it safe to assume that the README can be updated, and additionally, if one deployed an old version of the `k8s-cloudwatch-adapter` and has since updated it, that this APIService should be deleted?

```
kubectl delete apiservice v1beta1.custom.metrics.k8s.io
```

**Comment by chankh** [comment]
you are correct, custom.metrics is no longer being used in the adapter, so it is save to delete the apiservice if you had that created from an older version. I will update the readme.
