### ISSUE TITLE
lots of forbidden requests

### ISSUE THREAD

**Issue by ghostsquad** [awslabs/k8s-cloudwatch-adapter#27]
```
I0410 20:33:55.393355       1 authorization.go:73] Forbidden: "/", Reason: ""
I0410 20:33:55.393391       1 wrap.go:47] GET /: (80.215µs) 403 [Go-http-client/2.0 10.72.160.100:46374]
```

I'm seeing lots of log messages like this in one of my AWS EKS 1.14 Clusters

But I'm not sure where this is coming from. My manifests mirror that in this repo, with the addition of a kube2iam annotation.

**Comment by ghostsquad** [comment]
If this is attempting to get metrics from a node at IP `10.72.160.100` then that's a problem, as that node no longer exists.

**Comment by ghostsquad** [comment]
nvm, I think this issue is due the API server not being able to communicate with this pod. 10.72.160.100 appears to be the IP of the k8s-cloudwatch-adapter pod.

**Comment by piotr-struzik** [comment]
I'm facing the same problem 
How did you solve yours ?
