### ISSUE TITLE
Many failures related to external metrics at kube-apiserver logs.

### ISSUE THREAD

**Issue by markrity** [awslabs/k8s-cloudwatch-adapter#29]
Hi I recently have seen that we are getting a lot of logs related to external metrics on our EKS cluster.

![kube-apiserver logst](https://i.imgur.com/nNtTIky.png "kube-apiserver logs")

Cluster version : 1.15
Adapter version : 0.8.0 used latest deployment.
Checked api services we have no v1beta1.custom.metrics.k8s.io there , since I have seen it should be there anymore.

What can be the cause for this issues?

**Comment by chankh** [comment]
seems related to this https://github.com/kubernetes-sigs/metrics-server/issues/27

**Comment by markrity** [comment]
@chankh Yea it might be, thanks for pointing on it :)
