### ISSUE TITLE
cannot get queue: AWS.SimpleQueueService.NonExistentQueue

### ISSUE THREAD

**Issue by Urahara** [awslabs/k8s-cloudwatch-adapter#3]
I trying to use this project to migrate my applications from EC2/AutoScalling to EKS/K8s, because on AutoScalling i use SQS Metrics to scale my instances. 

I tried to follow all README, but i really didn't know what todo on Prerequsites, my kubectl is configured to my main account on aws that have all permissions to make all stuff and i have the sqs queue created. 

But when i get logs from pods, what should i do to make this work? 

I find i really bit confused all this permissions that i have to configured just to use a simple k8 cluster. :(

Thanks!!

> using AWS Region: us-east-1
> listening to queue: helloworld
> cannot get queue: AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist or you do not have access to it.
> 	status code: 400, request id: 8be62292-3a6a-5227-bc25-77cd06f9e3c9
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7582c6]
> 
> goroutine 1 [running]:
> main.main()
> 	/go/src/consumer/main.go:57 +0x4e6

**Comment by chankh** [comment]
It looks like your pods do not have the right IAM permissions, please take a look at `kube2iam` which is a project that allow you to attach IAM policies to pods running in k8s.
