### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by plumdog** [awslabs/k8s-cloudwatch-adapter#41]
Is a helm chart available, to allow configuration of some of the choices made in `deploy/adapter.yaml`.

Also, the install instructions don't make any use of `deploy/crd.yaml`, which is another thing that helm chart could handle.

**Comment by chankh** [comment]
Good suggestion, and thanks for reminding, I've merged `deploy/crd.yaml` into `deploy/adapter.yaml` so just deploying with `adapter.yaml` would do. 

Feel free to submit a PR to add a helm chart, or I can add that when I have some free cycles.

**Comment by ellisvalentiner** [comment]
@plumdog a Helm chart was added in #45 could you give it a try?

**Comment by mayppong** [comment]
It would be nice if the helm chart would be hosted for us. You can already get Travis to build the package for you, so it's not a lot of work additional. That way, as a user, I don't have to check out the repo first to install it through helm.
Or alternatively, you could provide a kustomize file as well.
If the repo admin would enable the repo setting side, I'm happy to submit the code change :)

**Comment by chankh** [comment]
doing that in #49
