### ISSUE TITLE
Use default EKS IRSA ServiceAccount annotation in helm chart

### ISSUE THREAD

**Issue by max-rocket-internet** [awslabs/k8s-cloudwatch-adapter#47]
Currently in it's using `iam.amazonaws.com/role`: https://github.com/awslabs/k8s-cloudwatch-adapter/blob/master/chart/templates/serviceaccount.yaml#L8

But I think it should be using `eks.amazonaws.com/role-arn` since it's the proper annotation on AWS EKS?

**Comment by Shivam9268** [comment]
Also Security Context needs to be added to the deployment as in #46
