### ISSUE TITLE
Please update the charts in helm hub

### ISSUE THREAD

**Issue by sparky005** [awslabs/k8s-cloudwatch-adapter#63]
Hello! It looks like the charts in the helm hub have not been updated to match what's in master. Specifically [this commit](https://github.com/awslabs/k8s-cloudwatch-adapter/commit/3adf572555dd86d1c39128a1bdd54f4e28f7f172) (and probably a few others) aren't present in the helm chart releases. 

Can you please update the charts in the helm hub to match the latest fixes in master? Otherwise we can't set the IAM role for the service account, and possibly other fixes are missing.

**Comment by chankh** [comment]
Updated, thanks.

**Comment by sparky005** [comment]
Thanks @chankh. Was there a new version published? I still only see `0.2.0` in helm hub, published on Sep 17.

**Comment by chankh** [comment]
@sparky005 it is updated now :)
